### ISSUE TITLE
Incompatible with Python 3.8

### ISSUE THREAD

**Issue by hongquan** [KnightConan/named_enum#66]
This code:

https://github.com/KnightConan/named_enum/blob/f170041b72dc93e2c6dfa28ffa3f6853ea5ad50a/named_enum/__init__.py#L118

is following Python 3.7:

https://github.com/python/cpython/blob/041bfafeb00b0e5e565986b01c00bf9cddce3b4c/Lib/enum.py#L135

while in Python3.8, it should be:

```
metacls._get_mixins_(cls, bases)
```

**Comment by KnightConan** [comment]
Hi @hongquan,
thanks for the feedback, I will correct it and release a bug fix version in pypi. 
Best,
Zhiwei
